_target_: src.losses.combined.CombinedLoss
alpha: 0.7
masked_mse:
  _target_: src.losses.masked_mse.MaskedMSELoss
  foreground_weight: 100.0
  sigmoid: true
soft_cldice:
  _target_: src.losses.soft_cldice.SoftCLDiceLoss
  iter_: 5
  smooth: 1.0
  sigmoid: true
